In [ ]:
import numpy as np
import tensorflow as tf
import sklearn
import pandas as pd
import os
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
overall_list = pd.read_csv('./drive/MyDrive/ds/item/overall_list.csv', sep=',', encoding='utf-8')
detail_list = pd.read_csv('./drive/MyDrive/ds/item/detail_list.csv', sep=',', encoding='utf-8')

In [ ]:
overall_list.head()

id  avg_rating  n_reviews  ...  n_rate_2  n_rate_1  rate_with_img
0  112329645         4.5         20  ...         1         0              0
1    2454355         4.7        365  ...         4        10             60
2    2454359         4.8        432  ...         2        10             58
3    2454353         4.8        367  ...         2        10             60
4   98565212         4.7        276  ...         3        13             49

[5 rows x 9 columns]

In [ ]:
detail_list.head()

id  ...    main_category
0  112329645  ...  bach-hoa-online
1    2454355  ...  bach-hoa-online
2    2454359  ...  bach-hoa-online
3    2454353  ...  bach-hoa-online
4   98565212  ...  bach-hoa-online

[5 rows x 12 columns]

In [ ]:
full_df = pd.merge(detail_list, overall_list, how='inner', on='id')
full_df.head(3)

id  ... rate_with_img
0  112329645  ...             0
1    2454355  ...            60
2    2454359  ...            58

[3 rows x 20 columns]

In [ ]:
full_df.dropna(subset=['n_sold'], inplace=True)

In [ ]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22958 entries, 0 to 24778
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             22958 non-null  int64  
 1   name           22958 non-null  object 
 2   category       22958 non-null  object 
 3   brand          21270 non-null  object 
 4   price          22958 non-null  int64  
 5   discount       22958 non-null  int64  
 6   discount_rate  22958 non-null  int64  
 7   mota           22956 non-null  object 
 8   image_url      22958 non-null  object 
 9   n_sold         22958 non-null  float64
 10  rank           15592 non-null  float64
 11  main_category  22958 non-null  object 
 12  avg_rating     22958 non-null  float64
 13  n_reviews      22958 non-null  int64  
 14  n_rate_5       22958 non-null  int64  
 15  n_rate_4       22958 non-null  int64  
 16  n_rate_3       22958 non-null  int64  
 17  n_rate_2       22958 non-null  int64  
 18  n_rate

In [ ]:
full_df.loc[full_df['price'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['avg_rating'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['n_reviews'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['rank'].isnull()]

id  ... rate_with_img
9       98190526  ...             3
28      54076939  ...             0
56       2287771  ...             1
71     114684809  ...             0
78      21224416  ...             3
...          ...  ...           ...
24768   10640271  ...            -1
24771  111782274  ...            -1
24772   10075988  ...             0
24777  119438252  ...            -1
24778    1705613  ...             0

[7366 rows x 20 columns]

In [ ]:
full_df['rank'] = full_df['rank'].replace(np.nan, 0)

In [ ]:
full_df['rate_with_img'] = full_df['rate_with_img'].replace(-1, 0)

In [ ]:
full_df.loc[full_df['rank'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['rate_with_img'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['n_rate_5'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['n_rate_4'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['n_rate_3'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['n_rate_2'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['n_rate_1'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['main_category'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['discount'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
full_df.loc[full_df['discount_rate'].isnull()]

Empty DataFrame
Columns: [id, name, category, brand, price, discount, discount_rate, mota, image_url, n_sold, rank, main_category, avg_rating, n_reviews, n_rate_5, n_rate_4, n_rate_3, n_rate_2, n_rate_1, rate_with_img]
Index: []

In [ ]:
y = full_df['n_sold']
print(y.shape)

(22958,)


In [ ]:
category = pd.get_dummies(full_df['main_category'], drop_first=True)

In [ ]:
price=full_df[['price']]
avg_rating = full_df[['avg_rating']]
n_reviews=full_df[['n_reviews']]
discount = full_df[['discount']]
discount_rate = full_df[['discount_rate']]
rank = full_df[['rank']]
n_rate_5 = full_df[['n_rate_5']]
n_rate_4 = full_df[['n_rate_4']]
n_rate_3 = full_df[['n_rate_3']]
n_rate_2 = full_df[['n_rate_2']]
n_rate_1 = full_df[['n_rate_1']]
rate_with_img = full_df[['rate_with_img']]

In [ ]:
class Metrics():
    def computeMSE(y_true, y_pred):
        return np.mean((y_true-y_pred)**2)

    def computeMAE(y_true, y_pred):
        return np.mean(np.abs(y_true-y_pred))

    def computeSIA(y_true, y_pred, eps=500): 
        error = np.abs(y_true - y_pred)
        res = np.mean(((error - eps) < 0 ) & (y_pred >= 0))
        return res

In [ ]:
feature_list = [category, 
                price,
                avg_rating, 
                n_reviews, 
                discount,
                discount_rate,
                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,
                # rate_with_img

                ]

In [ ]:
X = np.hstack(feature_list)
X

array([[     0,      0,      0, ...,  10000,      0,      0],
       [     0,      0,      0, ..., 360000,      0,      0],
       [     0,      0,      0, ..., 360000,      0,      0],
       ...,
       [     0,      0,      0, ...,  89000,      0,      0],
       [     0,      0,      0, ...,   5000,      0,      0],
       [     0,      0,      0, ..., 499000,      0,      0]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 27) (14692,)
(3674, 27) (3674,)
(4592, 27) (4592,)


<h1>Random Forest Regression</h1>

In [ ]:
model = RandomForestRegressor()
model = model.fit(X_train, y_train)

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

490.3853639524255
731.0752183481665
677.0451009977015


In [ ]:
#Compute SIA_1000 metrics
SIA_train = Metrics.computeSIA(y_train, model.predict(X_train), 1000)
SIA_val = Metrics.computeSIA(y_val, model.predict(X_val), 1000)
SIA_test = Metrics.computeSIA(y_test, model.predict(X_test), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9704601143479444
0.9246053347849755
0.9355400696864111


In [ ]:
#Compute SIA_500 metrics
SIA_train = Metrics.computeSIA(y_train, model.predict(X_train), 500)
SIA_val = Metrics.computeSIA(y_val, model.predict(X_val), 500)
SIA_test = Metrics.computeSIA(y_test, model.predict(X_test), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9433024775387966
0.8794229722373434
0.8791376306620209


In [ ]:
#Compute SIA_200 metrics
SIA_train = Metrics.computeSIA(y_train, model.predict(X_train), 200)
SIA_val = Metrics.computeSIA(y_val, model.predict(X_val), 200)
SIA_test = Metrics.computeSIA(y_test, model.predict(X_test), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8855159270351212
0.7808927599346761
0.7783101045296167


<h1>Linear Regression</h1>

In [ ]:
feature_list = [#category, 
                price,
                avg_rating, 
                n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 10) (14692,)
(3674, 10) (3674,)
(4592, 10) (4592,)


In [ ]:
normalizer = StandardScaler()
X_train = normalizer.fit_transform(X_train)

In [ ]:
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

LinearRegression()

In [ ]:
model.coef_

array([  -86.18312108,    67.44878877,  1173.77229876,     3.22779997,
         -22.80756928,  1834.66919537, -2755.55217972,  1174.06818094,
        -419.38787617,   539.9321603 ])

In [ ]:
print(np.where(model.coef_>1e4))
print(np.where(model.coef_>1e3))
print(np.where(model.coef_>1e2))

(array([], dtype=int64),)
(array([2, 5, 7]),)
(array([2, 5, 7, 9]),)


In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

694.1867283028328
615.256029143018
558.5591237085193


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8959978219439151
0.8922155688622755
0.9002613240418118


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.7893411380343044
0.7920522591181274
0.7948606271777003


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.5068064252654506
0.5059880239520959
0.5067508710801394


In [ ]:
from sklearn.linear_model import Ridge

alphas = np.linspace(0.001, 10, num=100)
best_val = np.inf
best_alpha = -1
model = None
for alpha in alphas:
    tmp_model = Ridge(alpha)
    tmp_model.fit(X_train ,y_train)
    mae_val = Metrics.computeMAE(y_val, tmp_model.predict(X_val))
    if mae_val < best_val:
        best_val = mae_val
        model = tmp_model
        best_alpha = alpha

print("Best cross-validation MAE: {} with alpha: {}".format(best_val, best_alpha))

Best cross-validation MAE: 611.7890488551732 with alpha: 10.0


In [ ]:
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

690.9897883916354
611.7890488551732
555.1870671166039


In [ ]:
print(model.coef_)

[  -85.54513799    67.38190779  1164.118237       2.95244223
   -22.57500996  1815.14884101 -2701.56100175  1144.01614339
  -414.98631283   537.6191186 ]


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8969507214810781
0.8924877517691889
0.9011324041811847


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.7908385515927036
0.7931409907457811
0.7957317073170732


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.5085760958344677
0.5073489384866631
0.508493031358885


<h1>Mean Encoding</h1>

In [ ]:
df_train, df_test = train_test_split(full_df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_train, test_size=0.2, random_state=1)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(14692, 20)
(3674, 20)
(4592, 20)


In [ ]:
category_dict = df_train.groupby("main_category").agg(["mean"])["n_sold"].to_dict()['mean']
category_dict

{'bach-hoa-online': 1560.9675324675325,
 'balo-va-vali': 110.20461538461538,
 'dien-gia-dung': 522.2282430213464,
 'dien-thoai-may-tinh-bang': 256.2821782178218,
 'dien-tu-dien-lanh': 89.35604770017036,
 'do-choi-me-be': 1587.7282442748092,
 'dong-ho-va-trang-suc': 53.70625,
 'giay-dep-nam': 70.8250773993808,
 'giay-dep-nu': 70.74963396778917,
 'hang-quoc-te': 116.38679245283019,
 'lam-dep-suc-khoe': 7003.153846153846,
 'laptop-may-vi-tinh-linh-kien': 275.5338461538461,
 'may-anh': 86.37781629116118,
 'nha-cua-doi-song': 888.5884146341464,
 'nha-sach-tiki': 3432.973988439306,
 'o-to-xe-may-xe-dap': 138.35616438356163,
 'phu-kien-thoi-trang': 147.30756843800322,
 'the-thao-da-ngoai': 206.6294498381877,
 'thiet-bi-kts-phu-kien-so': 513.6534954407294,
 'thoi-trang-nam': 251.0316742081448,
 'thoi-trang-nu': 116.02875399361022,
 'thuc-pham-tuoi-song': 416.70814132104454,
 'tui-thoi-trang-nam': 145.18870967741935,
 'tui-vi-nu': 41.661417322834644,
 'voucher-dich-vu': 4482.320185614849}

In [ ]:
category = full_df['main_category'].map(category_dict).fillna(0)
category.unique()

array([1560.96753247,  110.20461538,  522.22824302,  256.28217822,
         89.3560477 , 1587.72824427,   53.70625   ,   70.8250774 ,
         70.74963397,  116.38679245, 7003.15384615,  275.53384615,
         86.37781629,  888.58841463, 3432.97398844,  138.35616438,
        147.30756844,  206.62944984,  513.65349544,  251.03167421,
        116.02875399,  416.70814132,  145.18870968,   41.66141732,
       4482.32018561])

In [ ]:
price=full_df[['price']]
avg_rating = full_df[['avg_rating']]
n_reviews=full_df[['n_reviews']]
discount = full_df[['discount']]
discount_rate = full_df[['discount_rate']]
rank = full_df[['rank']]

In [ ]:
feature_list = [category[:, None], 
                price,
                avg_rating, 
                n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  """Entry point for launching an IPython kernel.


In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 6) (14692,)
(3674, 6) (3674,)
(4592, 6) (4592,)


In [ ]:
y_train == df_train['n_sold'].to_numpy()

22389    True
12264    True
13537    True
23360    True
2743     True
         ... 
17573    True
16810    True
18842    True
7276     True
6133     True
Name: n_sold, Length: 14692, dtype: bool

In [ ]:
normalizer = StandardScaler()
X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

LinearRegression()

In [ ]:
model.coef_

array([ 761.35817824,  -31.78893901,  210.79108268, 1177.51529756,
         18.55661086,  -73.9814233 ])

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

744.998501975427
649.0983449701644
602.8182904364868


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8569970051728832
0.8538377789874796
0.8660714285714286


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.7630683365096651
0.7610234077299945
0.764808362369338


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.6542335965151103
0.6545998911268373
0.6607142857142857


In [ ]:
df_train, df_test = train_test_split(full_df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_train, test_size=0.2, random_state=1)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(14692, 20)
(3674, 20)
(4592, 20)


In [ ]:
category_dict = df_train.groupby("main_category").agg(["mean"])["n_sold"].to_dict()['mean']
category_dict

{'bach-hoa-online': 1560.9675324675325,
 'balo-va-vali': 110.20461538461538,
 'dien-gia-dung': 522.2282430213464,
 'dien-thoai-may-tinh-bang': 256.2821782178218,
 'dien-tu-dien-lanh': 89.35604770017036,
 'do-choi-me-be': 1587.7282442748092,
 'dong-ho-va-trang-suc': 53.70625,
 'giay-dep-nam': 70.8250773993808,
 'giay-dep-nu': 70.74963396778917,
 'hang-quoc-te': 116.38679245283019,
 'lam-dep-suc-khoe': 7003.153846153846,
 'laptop-may-vi-tinh-linh-kien': 275.5338461538461,
 'may-anh': 86.37781629116118,
 'nha-cua-doi-song': 888.5884146341464,
 'nha-sach-tiki': 3432.973988439306,
 'o-to-xe-may-xe-dap': 138.35616438356163,
 'phu-kien-thoi-trang': 147.30756843800322,
 'the-thao-da-ngoai': 206.6294498381877,
 'thiet-bi-kts-phu-kien-so': 513.6534954407294,
 'thoi-trang-nam': 251.0316742081448,
 'thoi-trang-nu': 116.02875399361022,
 'thuc-pham-tuoi-song': 416.70814132104454,
 'tui-thoi-trang-nam': 145.18870967741935,
 'tui-vi-nu': 41.661417322834644,
 'voucher-dich-vu': 4482.320185614849}

In [ ]:
category = full_df['main_category'].map(category_dict).fillna(0)
category.unique()

array([1560.96753247,  110.20461538,  522.22824302,  256.28217822,
         89.3560477 , 1587.72824427,   53.70625   ,   70.8250774 ,
         70.74963397,  116.38679245, 7003.15384615,  275.53384615,
         86.37781629,  888.58841463, 3432.97398844,  138.35616438,
        147.30756844,  206.62944984,  513.65349544,  251.03167421,
        116.02875399,  416.70814132,  145.18870968,   41.66141732,
       4482.32018561])

In [ ]:
price=full_df[['price']]
avg_rating = full_df[['avg_rating']]
n_reviews=full_df[['n_reviews']]
discount = full_df[['discount']]
discount_rate = full_df[['discount_rate']]
rank = full_df[['rank']]

In [ ]:
feature_list = [#category[:, None], 
                price,
                avg_rating, 
                n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 5) (14692,)
(3674, 5) (3674,)
(4592, 5) (4592,)


In [ ]:
y_train == df_train['n_sold'].to_numpy()

22389    True
12264    True
13537    True
23360    True
2743     True
         ... 
17573    True
16810    True
18842    True
7276     True
6133     True
Name: n_sold, Length: 14692, dtype: bool

In [ ]:
normalizer = StandardScaler()
X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

LinearRegression()

In [ ]:
model.coef_

array([ -48.93053255,   63.97676582, 1391.0808008 ,   -8.93329152,
        -18.84029337])

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

601.720766481603
505.34609654128735
474.32458792470084


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9166212904982304
0.9164398475775721
0.9213850174216028


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8416825483256194
0.8415895481763745
0.8484320557491289


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.6429349305744623
0.6347305389221557
0.6361062717770035


<h1>Neural Network</h1>

In [ ]:
df_train, df_test = train_test_split(full_df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_train, test_size=0.2, random_state=1)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(14692, 20)
(3674, 20)
(4592, 20)


In [ ]:
category_dict = df_train.groupby("main_category").agg(["mean"])["n_sold"].to_dict()['mean']
category = full_df['main_category'].map(category_dict).fillna(0)[:,None]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  


In [ ]:
feature_list = [category, 
                price,
                avg_rating, 
                n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 6) (14692,)
(3674, 6) (3674,)
(4592, 6) (4592,)


In [ ]:
normalizer = StandardScaler()

X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=32,activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=64, activation ='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=1, activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01))
])

model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss = tf.keras.losses.mean_absolute_error,
              metrics=['mae'])

In [ ]:
if not os.path.exists("./drive/MyDrive/ds/item/models"):
    os.makedirs("./drive/MyDrive/ds/item/models")
mcp_save = tf.keras.callbacks.ModelCheckpoint(
    filepath="./drive/MyDrive/ds/item/models/sold_prediction_nn_model_mean.h5",
    save_weights_only=True,
    monitor='val_mae',
    mode='min',
    save_best_only=True) 

model.fit(X_train, y_train,
          epochs=300,
          batch_size=128,
          validation_data=(X_val, y_val),
          callbacks=[mcp_save])

Epoch 1/300
115/115 [==============================] - 1s 8ms/step - loss: 622.6734 - mae: 622.1814 - val_loss: 567.7770 - val_mae: 567.1725
Epoch 2/300
115/115 [==============================] - 0s 3ms/step - loss: 608.5609 - mae: 607.6512 - val_loss: 547.3037 - val_mae: 546.0588
Epoch 3/300
115/115 [==============================] - 0s 2ms/step - loss: 584.2719 - mae: 582.5701 - val_loss: 516.5666 - val_mae: 514.3723
Epoch 4/300
115/115 [==============================] - 0s 3ms/step - loss: 555.6902 - mae: 552.8761 - val_loss: 485.7423 - val_mae: 482.2747
Epoch 5/300
115/115 [==============================] - 0s 3ms/step - loss: 529.4366 - mae: 525.2916 - val_loss: 456.7911 - val_mae: 451.9896
Epoch 6/300
115/115 [==============================] - 0s 3ms/step - loss: 506.8376 - mae: 501.3775 - val_loss: 430.4622 - val_mae: 424.4178
Epoch 7/300
115/115 [==============================] - 0s 3ms/step - loss: 489.5298 - mae: 482.9365 - val_loss: 411.2242 - val_mae: 404.2844
Epoch 8/300
1

In [ ]:
model.load_weights("./drive/MyDrive/ds/item/models/sold_prediction_nn_model_mean.h5")

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train).squeeze())
mae_val = Metrics.computeMAE(y_val, model.predict(X_val).squeeze())
mae_test = Metrics.computeMAE(y_test, model.predict(X_test).squeeze())

print(mae_train)
print(mae_val)
print(mae_test)

436.503766418331
346.3489487530034
310.8278100167106


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9437108630547236
0.9425694066412629
0.9433797909407665


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9027361829567111
0.9003810560696788
0.8980836236933798


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.814592975769126
0.8127381600435493
0.8081445993031359


In [ ]:
category = pd.get_dummies(full_df['main_category'], drop_first=True)

In [ ]:
feature_list = [category, 
                price,
                avg_rating, 
                n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 29) (14692,)
(3674, 29) (3674,)
(4592, 29) (4592,)


In [ ]:
normalizer = StandardScaler()

X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=32,activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=64, activation ='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=1, activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01))
])

model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss = tf.keras.losses.mean_absolute_error,
              metrics=['mae'])

In [ ]:
if not os.path.exists("./drive/MyDrive/ds/item/models"):
    os.makedirs("./drive/MyDrive/ds/item/models")
mcp_save = tf.keras.callbacks.ModelCheckpoint(
    filepath="./drive/MyDrive/ds/item/models/sold_prediction_nn_model_onehot.h5",
    save_weights_only=True,
    monitor='val_mae',
    mode='min',
    save_best_only=True)  #save model's weights with highest validation performance

model.fit(X_train, y_train,
          epochs=300,
          batch_size=128,
          validation_data=(X_val, y_val),
          callbacks=[mcp_save])

Epoch 1/300
115/115 [==============================] - 1s 5ms/step - loss: 620.7272 - mae: 619.9804 - val_loss: 562.9474 - val_mae: 561.9979
Epoch 2/300
115/115 [==============================] - 0s 3ms/step - loss: 600.8910 - mae: 599.5870 - val_loss: 537.8864 - val_mae: 536.2459
Epoch 3/300
115/115 [==============================] - 0s 3ms/step - loss: 577.2390 - mae: 575.3463 - val_loss: 513.2921 - val_mae: 511.0677
Epoch 4/300
115/115 [==============================] - 0s 3ms/step - loss: 555.8559 - mae: 553.3810 - val_loss: 492.1199 - val_mae: 489.3695
Epoch 5/300
115/115 [==============================] - 0s 3ms/step - loss: 538.0525 - mae: 535.0479 - val_loss: 471.2836 - val_mae: 467.9500
Epoch 6/300
115/115 [==============================] - 0s 3ms/step - loss: 521.6779 - mae: 518.0389 - val_loss: 451.2631 - val_mae: 447.3191
Epoch 7/300
115/115 [==============================] - 0s 3ms/step - loss: 507.3076 - mae: 503.0084 - val_loss: 431.3919 - val_mae: 426.7642
Epoch 8/300
1

In [ ]:
model.load_weights("./drive/MyDrive/ds/item/models/sold_prediction_nn_model_onehot.h5")

In [ ]:
mae_train = Metrics.computeMAE(y_train, model.predict(X_train).squeeze())
mae_val = Metrics.computeMAE(y_val, model.predict(X_val).squeeze())
mae_test = Metrics.computeMAE(y_test, model.predict(X_test).squeeze())

print(mae_train)
print(mae_val)
print(mae_test)

426.979545314083
342.91673481852933
305.61968279661096


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9453444051184318
0.9417528579205225
0.944904181184669


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.907024230873945
0.9014697876973327
0.9039634146341463


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8226926218350122
0.8143712574850299
0.8118466898954704


<H3>Affection Analysis By n_reviews And avg_rating Features</H3>

In [ ]:
feature_list = [category, 
                price,
                #avg_rating, 
                #n_reviews, 
                discount,
                discount_rate,
                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,
                # rate_with_img

                ]

In [ ]:
X = np.hstack(feature_list)
X

array([[     0,      0,      0, ...,  10000,      0,      0],
       [     0,      0,      0, ..., 360000,      0,      0],
       [     0,      0,      0, ..., 360000,      0,      0],
       ...,
       [     0,      0,      0, ...,  89000,      0,      0],
       [     0,      0,      0, ...,   5000,      0,      0],
       [     0,      0,      0, ..., 499000,      0,      0]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 27) (14692,)
(3674, 27) (3674,)
(4592, 27) (4592,)


In [ ]:
model = RandomForestRegressor()
model = model.fit(X_train, y_train)

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

490.4844755633252
736.4874976147349
688.279906949656


In [ ]:
#Compute SIA_1000 metrics
SIA_train = Metrics.computeSIA(y_train, model.predict(X_train), 1000)
SIA_val = Metrics.computeSIA(y_val, model.predict(X_val), 1000)
SIA_test = Metrics.computeSIA(y_test, model.predict(X_test), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9384699156003267
0.8832335329341318
0.8815331010452961


In [ ]:
#Compute SIA_500 metrics
SIA_train = Metrics.computeSIA(y_train, model.predict(X_train), 500)
SIA_val = Metrics.computeSIA(y_val, model.predict(X_val), 500)
SIA_test = Metrics.computeSIA(y_test, model.predict(X_test), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8879662401306834
0.8032117583015786
0.7998693379790941


In [ ]:
#Compute SIA_200 metrics
SIA_train = Metrics.computeSIA(y_train, model.predict(X_train), 200)
SIA_val = Metrics.computeSIA(y_val, model.predict(X_val), 200)
SIA_test = Metrics.computeSIA(y_test, model.predict(X_test), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.7732099101551865
0.6317365269461078
0.6319686411149826


In [ ]:
feature_list = [#category, 
                price,
                #avg_rating, 
                #n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 3) (14692,)
(3674, 3) (3674,)
(4592, 3) (4592,)


In [ ]:
normalizer = StandardScaler()
X_train = normalizer.fit_transform(X_train)

In [ ]:
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

LinearRegression()

In [ ]:
model.coef_

array([-60.87842076, -44.11495952, 161.86857141])

In [ ]:
print(np.where(model.coef_>1e4))
print(np.where(model.coef_>1e3))
print(np.where(model.coef_>1e2))

(array([], dtype=int64),)
(array([], dtype=int64),)
(array([2]),)


In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

906.1155889328231
856.6267012729319
778.1888049766019


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9273754424176422
0.9281437125748503
0.9287891986062717


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.39293493057446227
0.39439303211758303
0.40135017421602787


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.07806969779471822
0.07947740881872618
0.07992160278745644


In [ ]:
from sklearn.linear_model import Ridge

alphas = np.linspace(0.001, 10, num=100)
best_val = np.inf
best_alpha = -1
model = None
for alpha in alphas:
    tmp_model = Ridge(alpha)
    tmp_model.fit(X_train ,y_train)
    mae_val = Metrics.computeMAE(y_val, tmp_model.predict(X_val))
    if mae_val < best_val:
        best_val = mae_val
        model = tmp_model
        best_alpha = alpha

print("Best cross-validation MAE: {} with alpha: {}".format(best_val, best_alpha))

Best cross-validation MAE: 856.6267015760864 with alpha: 0.001


In [ ]:
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

906.1155892251361
856.6267015760864
778.1888053211018


In [ ]:
print(model.coef_)

[-60.8784186  -44.11495498 161.86855951]


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9273754424176422
0.9281437125748503
0.9287891986062717


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.39293493057446227
0.39439303211758303
0.40135017421602787


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.07806969779471822
0.07947740881872618
0.07992160278745644


In [ ]:
df_train, df_test = train_test_split(full_df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_train, test_size=0.2, random_state=1)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(14692, 20)
(3674, 20)
(4592, 20)


In [ ]:
category_dict = df_train.groupby("main_category").agg(["mean"])["n_sold"].to_dict()['mean']
category_dict

{'bach-hoa-online': 1560.9675324675325,
 'balo-va-vali': 110.20461538461538,
 'dien-gia-dung': 522.2282430213464,
 'dien-thoai-may-tinh-bang': 256.2821782178218,
 'dien-tu-dien-lanh': 89.35604770017036,
 'do-choi-me-be': 1587.7282442748092,
 'dong-ho-va-trang-suc': 53.70625,
 'giay-dep-nam': 70.8250773993808,
 'giay-dep-nu': 70.74963396778917,
 'hang-quoc-te': 116.38679245283019,
 'lam-dep-suc-khoe': 7003.153846153846,
 'laptop-may-vi-tinh-linh-kien': 275.5338461538461,
 'may-anh': 86.37781629116118,
 'nha-cua-doi-song': 888.5884146341464,
 'nha-sach-tiki': 3432.973988439306,
 'o-to-xe-may-xe-dap': 138.35616438356163,
 'phu-kien-thoi-trang': 147.30756843800322,
 'the-thao-da-ngoai': 206.6294498381877,
 'thiet-bi-kts-phu-kien-so': 513.6534954407294,
 'thoi-trang-nam': 251.0316742081448,
 'thoi-trang-nu': 116.02875399361022,
 'thuc-pham-tuoi-song': 416.70814132104454,
 'tui-thoi-trang-nam': 145.18870967741935,
 'tui-vi-nu': 41.661417322834644,
 'voucher-dich-vu': 4482.320185614849}

In [ ]:
category = full_df['main_category'].map(category_dict).fillna(0)
category.unique()

array([1560.96753247,  110.20461538,  522.22824302,  256.28217822,
         89.3560477 , 1587.72824427,   53.70625   ,   70.8250774 ,
         70.74963397,  116.38679245, 7003.15384615,  275.53384615,
         86.37781629,  888.58841463, 3432.97398844,  138.35616438,
        147.30756844,  206.62944984,  513.65349544,  251.03167421,
        116.02875399,  416.70814132,  145.18870968,   41.66141732,
       4482.32018561])

In [ ]:
price=full_df[['price']]
avg_rating = full_df[['avg_rating']]
n_reviews=full_df[['n_reviews']]
discount = full_df[['discount']]
discount_rate = full_df[['discount_rate']]
rank = full_df[['rank']]

In [ ]:
feature_list = [category[:, None], 
                price,
                #avg_rating, 
                #n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  """Entry point for launching an IPython kernel.


In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 4) (14692,)
(3674, 4) (3674,)
(4592, 4) (4592,)


In [ ]:
y_train == df_train['n_sold'].to_numpy()

22389    True
12264    True
13537    True
23360    True
2743     True
         ... 
17573    True
16810    True
18842    True
7276     True
6133     True
Name: n_sold, Length: 14692, dtype: bool

In [ ]:
normalizer = StandardScaler()
X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

LinearRegression()

In [ ]:
model.coef_

array([1037.95891916,  -28.77220149,   -2.9159493 ,   73.63172562])

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

794.788409641142
735.7410120978144
649.1302433846175


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8448815682003812
0.8451279259662493
0.850609756097561


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.772733460386605
0.7670114316820904
0.7722125435540069


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.5668390961067248
0.5642351660315732
0.5692508710801394


In [ ]:
df_train, df_test = train_test_split(full_df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_train, test_size=0.2, random_state=1)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(14692, 20)
(3674, 20)
(4592, 20)


In [ ]:
category_dict = df_train.groupby("main_category").agg(["mean"])["n_sold"].to_dict()['mean']
category_dict

{'bach-hoa-online': 1560.9675324675325,
 'balo-va-vali': 110.20461538461538,
 'dien-gia-dung': 522.2282430213464,
 'dien-thoai-may-tinh-bang': 256.2821782178218,
 'dien-tu-dien-lanh': 89.35604770017036,
 'do-choi-me-be': 1587.7282442748092,
 'dong-ho-va-trang-suc': 53.70625,
 'giay-dep-nam': 70.8250773993808,
 'giay-dep-nu': 70.74963396778917,
 'hang-quoc-te': 116.38679245283019,
 'lam-dep-suc-khoe': 7003.153846153846,
 'laptop-may-vi-tinh-linh-kien': 275.5338461538461,
 'may-anh': 86.37781629116118,
 'nha-cua-doi-song': 888.5884146341464,
 'nha-sach-tiki': 3432.973988439306,
 'o-to-xe-may-xe-dap': 138.35616438356163,
 'phu-kien-thoi-trang': 147.30756843800322,
 'the-thao-da-ngoai': 206.6294498381877,
 'thiet-bi-kts-phu-kien-so': 513.6534954407294,
 'thoi-trang-nam': 251.0316742081448,
 'thoi-trang-nu': 116.02875399361022,
 'thuc-pham-tuoi-song': 416.70814132104454,
 'tui-thoi-trang-nam': 145.18870967741935,
 'tui-vi-nu': 41.661417322834644,
 'voucher-dich-vu': 4482.320185614849}

In [ ]:
category = full_df['main_category'].map(category_dict).fillna(0)
category.unique()

array([1560.96753247,  110.20461538,  522.22824302,  256.28217822,
         89.3560477 , 1587.72824427,   53.70625   ,   70.8250774 ,
         70.74963397,  116.38679245, 7003.15384615,  275.53384615,
         86.37781629,  888.58841463, 3432.97398844,  138.35616438,
        147.30756844,  206.62944984,  513.65349544,  251.03167421,
        116.02875399,  416.70814132,  145.18870968,   41.66141732,
       4482.32018561])

In [ ]:
price=full_df[['price']]
avg_rating = full_df[['avg_rating']]
n_reviews=full_df[['n_reviews']]
discount = full_df[['discount']]
discount_rate = full_df[['discount_rate']]
rank = full_df[['rank']]

In [ ]:
feature_list = [#category[:, None], 
                price,
                #avg_rating, 
                #n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 3) (14692,)
(3674, 3) (3674,)
(4592, 3) (4592,)


In [ ]:
y_train == df_train['n_sold'].to_numpy()

22389    True
12264    True
13537    True
23360    True
2743     True
         ... 
17573    True
16810    True
18842    True
7276     True
6133     True
Name: n_sold, Length: 14692, dtype: bool

In [ ]:
normalizer = StandardScaler()
X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

LinearRegression()

In [ ]:
model.coef_

array([-60.87842076, -44.11495952, 161.86857141])

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train))
mae_val = Metrics.computeMAE(y_val, model.predict(X_val))
mae_test = Metrics.computeMAE(y_test, model.predict(X_test))

print(mae_train)
print(mae_val)
print(mae_test)

906.1155889328231
856.6267012729319
778.1888049766019


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9273754424176422
0.9281437125748503
0.9287891986062717


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.39293493057446227
0.39439303211758303
0.40135017421602787


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.07806969779471822
0.07947740881872618
0.07992160278745644


In [ ]:
df_train, df_test = train_test_split(full_df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_train, test_size=0.2, random_state=1)
print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(14692, 20)
(3674, 20)
(4592, 20)


In [ ]:
category_dict = df_train.groupby("main_category").agg(["mean"])["n_sold"].to_dict()['mean']
category = full_df['main_category'].map(category_dict).fillna(0)[:,None]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  


In [ ]:
feature_list = [category, 
                price,
                #avg_rating, 
                #n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 4) (14692,)
(3674, 4) (3674,)
(4592, 4) (4592,)


In [ ]:
normalizer = StandardScaler()

X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=32,activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=64, activation ='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=1, activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01))
])

model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss = tf.keras.losses.mean_absolute_error,
              metrics=['mae'])

In [ ]:
if not os.path.exists("./drive/MyDrive/ds/item/models"):
    os.makedirs("./drive/MyDrive/ds/item/models")
mcp_save = tf.keras.callbacks.ModelCheckpoint(
    filepath="./drive/MyDrive/ds/item/models/no_rating_reviews_sold_prediction_nn_model_mean.h5",
    save_weights_only=True,
    monitor='val_mae',
    mode='min',
    save_best_only=True) 

model.fit(X_train, y_train,
          epochs=300,
          batch_size=128,
          validation_data=(X_val, y_val),
          callbacks=[mcp_save])

Epoch 1/300
115/115 [==============================] - 1s 6ms/step - loss: 622.2410 - mae: 621.7612 - val_loss: 567.1868 - val_mae: 566.5792
Epoch 2/300
115/115 [==============================] - 0s 4ms/step - loss: 610.5894 - mae: 609.7093 - val_loss: 555.9199 - val_mae: 554.8015
Epoch 3/300
115/115 [==============================] - 0s 4ms/step - loss: 601.1974 - mae: 599.9011 - val_loss: 547.9181 - val_mae: 546.4354
Epoch 4/300
115/115 [==============================] - 1s 4ms/step - loss: 594.8399 - mae: 593.2064 - val_loss: 543.0566 - val_mae: 541.2550
Epoch 5/300
115/115 [==============================] - 1s 5ms/step - loss: 591.2558 - mae: 589.3097 - val_loss: 540.7202 - val_mae: 538.6079
Epoch 6/300
115/115 [==============================] - 0s 4ms/step - loss: 589.5242 - mae: 587.3225 - val_loss: 539.7886 - val_mae: 537.5050
Epoch 7/300
115/115 [==============================] - 1s 5ms/step - loss: 588.5969 - mae: 586.2681 - val_loss: 539.0517 - val_mae: 536.6438
Epoch 8/300
1

In [ ]:
model.load_weights("./drive/MyDrive/ds/item/models/no_rating_reviews_sold_prediction_nn_model_mean.h5")

In [ ]:
#Compute MAE metrics
mae_train = Metrics.computeMAE(y_train, model.predict(X_train).squeeze())
mae_val = Metrics.computeMAE(y_val, model.predict(X_val).squeeze())
mae_test = Metrics.computeMAE(y_test, model.predict(X_test).squeeze())

print(mae_train)
print(mae_val)
print(mae_test)

559.311007583984
503.596648943395
428.76404714452605


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9248570650694256
0.9262384322264562
0.9259581881533101


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8718350122515655
0.8715296679368536
0.8754355400696864


In [ ]:
#Compute SIA metrics
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.755649332970324
0.7544910179640718
0.7578397212543554


In [ ]:
category = pd.get_dummies(full_df['main_category'], drop_first=True)

In [ ]:
feature_list = [category, 
                price,
                #avg_rating, 
                #n_reviews, 
                discount,
                discount_rate,

                # n_rate_5,
                # n_rate_4,
                # n_rate_3,
                # n_rate_2,
                # n_rate_1,

                ]

In [ ]:
X = np.hstack(feature_list)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(14692, 27) (14692,)
(3674, 27) (3674,)
(4592, 27) (4592,)


In [ ]:
normalizer = StandardScaler()

X_train = normalizer.fit_transform(X_train)
X_val = normalizer.transform(X_val)
X_test = normalizer.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=32,activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=64, activation ='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01)),
    tf.keras.layers.Dense(units=1, activation='relu', kernel_regularizer=tf.keras.regularizers.L2(0.01))
])

model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss = tf.keras.losses.mean_absolute_error,
              metrics=['mae'])

In [ ]:
if not os.path.exists("./drive/MyDrive/ds/item/models"):
    os.makedirs("./drive/MyDrive/ds/item/models")
mcp_save = tf.keras.callbacks.ModelCheckpoint(
    filepath="./drive/MyDrive/ds/item/models/no_rating_reviews_sold_prediction_nn_model_onehot.h5",
    save_weights_only=True,
    monitor='val_mae',
    mode='min',
    save_best_only=True)  #save model's weights with highest validation performance

model.fit(X_train, y_train,
          epochs=300,
          batch_size=128,
          validation_data=(X_val, y_val),
          callbacks=[mcp_save])

Epoch 1/300
115/115 [==============================] - 2s 9ms/step - loss: 618.7347 - mae: 617.9016 - val_loss: 560.4152 - val_mae: 559.3277
Epoch 2/300
115/115 [==============================] - 1s 6ms/step - loss: 600.2860 - mae: 598.8976 - val_loss: 541.9304 - val_mae: 540.2864
Epoch 3/300
115/115 [==============================] - 1s 5ms/step - loss: 585.1804 - mae: 583.3521 - val_loss: 529.9133 - val_mae: 527.9378
Epoch 4/300
115/115 [==============================] - 1s 5ms/step - loss: 575.2760 - mae: 573.1056 - val_loss: 521.8296 - val_mae: 519.5170
Epoch 5/300
115/115 [==============================] - 1s 5ms/step - loss: 569.2255 - mae: 566.7811 - val_loss: 516.6868 - val_mae: 514.1390
Epoch 6/300
115/115 [==============================] - 1s 5ms/step - loss: 565.4651 - mae: 562.7933 - val_loss: 512.7280 - val_mae: 509.9464
Epoch 7/300
115/115 [==============================] - 1s 5ms/step - loss: 563.1432 - mae: 560.2698 - val_loss: 510.0147 - val_mae: 507.0398
Epoch 8/300
1

In [ ]:
model.load_weights("./drive/MyDrive/ds/item/models/no_rating_reviews_sold_prediction_nn_model_onehot.h5")

In [ ]:
mae_train = Metrics.computeMAE(y_train, model.predict(X_train).squeeze())
mae_val = Metrics.computeMAE(y_val, model.predict(X_val).squeeze())
mae_test = Metrics.computeMAE(y_test, model.predict(X_test).squeeze())

print(mae_train)
print(mae_val)
print(mae_test)

549.7517588061032
499.98076884901974
422.4294120524961


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 1000)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 1000)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 1000)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.9258099646065886
0.9254218835057159
0.9261759581881533


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 500)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 500)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 500)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.8749659678736728
0.8750680457267284
0.876088850174216


In [ ]:
SIA_train = Metrics.computeSIA(y_train, np.clip(model.predict(X_train), 0,np.inf).squeeze(), 200)
SIA_val = Metrics.computeSIA(y_val, np.clip(model.predict(X_val).squeeze(), 0,np.inf), 200)
SIA_test = Metrics.computeSIA(y_test, np.clip(model.predict(X_test).squeeze(), 0,np.inf), 200)

print(SIA_train)
print(SIA_val)
print(SIA_test)

0.7632044650149742
0.7659227000544366
0.7619773519163763
